# Copyright (c) 2009, Giampaolo Rodola'. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from typing import Any

version: int
SSLEEP: int
SRUN: int
SZOMB: int
SSTOP: int
SIDL: int
SONPROC: int
SWAIT: int

PRNODEV: int

TCPS_CLOSED: int
TCPS_CLOSING: int
TCPS_CLOSE_WAIT: int
TCPS_LISTEN: int
TCPS_ESTABLISHED: int
TCPS_SYN_SENT: int
TCPS_SYN_RCVD: int
TCPS_FIN_WAIT_1: int
TCPS_FIN_WAIT_2: int
TCPS_LAST_ACK: int
TCPS_TIME_WAIT: int
TCPS_IDLE: int
TCPS_BOUND: int
PSUTIL_CONN_NONE: int

def proc_basic_info(*args, **kwargs) -> Any: ...
def proc_cpu_num(*args, **kwargs) -> Any: ...
def proc_cpu_times(*args, **kwargs) -> Any: ...
def proc_cred(*args, **kwargs) -> Any: ...
def proc_environ(*args, **kwargs) -> Any: ...
def proc_memory_maps(*args, **kwargs) -> Any: ...
def proc_name_and_args(*args, **kwargs) -> Any: ...
def proc_num_ctx_switches(*args, **kwargs) -> Any: ...
def query_process_thread(*args, **kwargs) -> Any: ...

def boot_time(*args, **kwargs) -> Any: ...
def cpu_count_cores(*args, **kwargs) -> Any: ...
def cpu_stats(*args, **kwargs) -> Any: ...
def disk_io_counters(*args, **kwargs) -> Any: ...
def disk_partitions(*args, **kwargs) -> Any: ...
def net_connections(*args, **kwargs) -> Any: ...
def net_if_stats(*args, **kwargs) -> Any: ...
def net_io_counters(*args, **kwargs) -> Any: ...
def per_cpu_times(*args, **kwargs) -> Any: ...
def swap_mem(*args, **kwargs) -> Any: ...

def check_pid_range(pid: int, /) -> None: ...
def set_debug(*args, **kwargs) -> Any: ...
