# Copyright (c) 2009, Jay Loden, Giampaolo Rodola', Landry Breuil
# (OpenBSD implementation), Ryo Onodera (NetBSD implementation).
# All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
from typing import Any

version: int
SIDL: int
SRUN: int
SSLEEP: int
SSTOP: int
SZOMB: int

if sys.platform.startswith(("freebsd", "midnightbsd")):
    SWAIT: int
    SLOCK: int

if sys.platform.startswith("openbsd"):
    SDEAD: int
    SONPROC: int

if sys.platform.startswith("netbsd"):
    SONPROC: int
    SSUSPENDED: int

TCPS_CLOSED: int
TCPS_CLOSING: int
TCPS_CLOSE_WAIT: int
TCPS_LISTEN: int
TCPS_ESTABLISHED: int
TCPS_SYN_SENT: int
TCPS_SYN_RECEIVED: int
TCPS_FIN_WAIT_1: int
TCPS_FIN_WAIT_2: int
TCPS_LAST_ACK: int
TCPS_TIME_WAIT: int
PSUTIL_CONN_NONE: int

def proc_cmdline(*args, **kwargs) -> Any: ...
def proc_cwd(*args, **kwargs) -> Any: ...
def proc_environ(*args, **kwargs) -> Any: ...
def proc_name(*args, **kwargs) -> Any: ...
def proc_num_fds(*args, **kwargs) -> Any: ...
def proc_oneshot_info(*args, **kwargs) -> Any: ...
def proc_open_files(*args, **kwargs) -> Any: ...
def proc_threads(*args, **kwargs) -> Any: ...

if (sys.platform.startswith(("freebsd", "midnightbsd")) or
    sys.platform.startswith("netbsd")):
    def proc_num_threads(*args, **kwargs) -> Any: ...

if sys.platform.startswith(("freebsd", "midnightbsd")):
    def proc_cpu_affinity_get(*args, **kwargs) -> Any: ...
    def proc_cpu_affinity_set(*args, **kwargs) -> Any: ...
    def proc_exe(*args, **kwargs) -> Any: ...
    def proc_getrlimit(*args, **kwargs) -> Any: ...
    def proc_memory_maps(*args, **kwargs) -> Any: ...
    def proc_net_connections(*args, **kwargs) -> Any: ...
    def proc_setrlimit(*args, **kwargs) -> Any: ...

def boot_time(*args, **kwargs) -> Any: ...
def cpu_count_logical(*args, **kwargs) -> Any: ...
def cpu_stats(*args, **kwargs) -> Any: ...
def cpu_times(*args, **kwargs) -> Any: ...
def disk_io_counters(*args, **kwargs) -> Any: ...
def disk_partitions(*args, **kwargs) -> Any: ...
def net_connections(*args, **kwargs) -> Any: ...
def net_io_counters(*args, **kwargs) -> Any: ...
def per_cpu_times(*args, **kwargs) -> Any: ...
def pids(*args, **kwargs) -> Any: ...
def swap_mem(*args, **kwargs) -> Any: ...
def virtual_mem(*args, **kwargs) -> Any: ...

if sys.platform.startswith("openbsd"):
    def users(*args, **kwargs) -> Any: ...

if (sys.platform.startswith(("freebsd", "midnightbsd"))
    or sys.platform.startswith("openbsd")):
    def cpu_freq(*args, **kwargs) -> Any: ...

if sys.platform.startswith(("freebsd", "midnightbsd")):
    def cpu_topology(*args, **kwargs) -> Any: ...
    def sensors_battery(*args, **kwargs) -> Any: ...
    def sensors_cpu_temperature(*args, **kwargs) -> Any: ...

def check_pid_range(pid: int, /) -> None: ...
def set_debug(*args, **kwargs) -> Any: ...
